def get_personal_objects():
     personal_objects = {
            "person": "A person",
            "cell phone": "A cell phone",
            "laptop": "A laptop",
            "book": "A book",
            "backpack": "A backpack",
            "handbag": "A handbag",
            "wallet": "A wallet",
            "keys": "A set of keys",
            "watch": "A wristwatch",
            "bottle": "A bottle",
            "cup": "A cup",
            "chair": "A chair",
            "remote": "A TV remote control",
            "keyboard": "A computer keyboard",
            "mouse": "A computer mouse",
            "tv": "A television",
            "glasses": "A pair of glasses",
            "headphones": "A pair of headphones",
            "umbrella": "An umbrella",
            "shoe": "A shoe",
            "sneakers": "A pair of sneakers",
            "toothbrush": "A toothbrush",
            "toothpaste": "A tube of toothpaste",
            "towel": "A towel",
            "mirror": "A mirror",
            "pillow": "A pillow",
            "blanket": "A blanket",
            "couch": "A couch",
            "refrigerator": "A refrigerator",
            "microwave": "A microwave oven",
            "oven": "An oven",
            "sink": "A sink",
            "spoon": "A spoon",
            "fork": "A fork",
            "knife": "A kitchen knife",
            "plate": "A plate",
            "fan": "A standing fan",
            "lamp": "A lamp",
            "desk": "A desk",
            "notebook": "A notebook",
            "pen": "A pen",
            "pencil": "A pencil",
            "scissors": "A pair of scissors",
            "broom": "A broom",
            "mop": "A mop",
            "trash can": "A trash can",
            "clock": "A wall clock",
        }
     
     return personal_objects